### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by PaienNate** [CerisWhite/Lantern#3]
I use 1.5 binary version and try to ExportPal with a 2GB file——then it throw this...
Seems there need a way to add memory for this?

**Comment by CerisWhite** [comment]
This is most likely because of the fact that the script is obfuscated. If you want to send me the .sav file in question, I can try to figure out a fix.

**Comment by PaienNate** [comment]
> This is most likely because of the fact that the script is obfuscated. If you want to set me the .sav file in question, I can try to figure out a fix.
[Level.zip](https://github.com/CerisWhite/Lantern/files/14134744/Level.zip)

Okay, btw, I use source code with my node and it works very well.

**Comment by CerisWhite** [comment]
Are you using Windows or Linux?

**Comment by PaienNate** [comment]
Windows.

**Comment by CerisWhite** [comment]
Please try with this build and let me know if another error comes up
[Lantern_dev_v1.5.zip](https://github.com/CerisWhite/Lantern/files/14134985/Lantern_dev_v1.5.zip)

Please note that this is an in-dev build so there may be other issues. I'm currently working on other features.

**Comment by PaienNate** [comment]
> Please try with this build and let me know if another error comes up [Lantern_dev_v1.5.zip](https://github.com/CerisWhite/Lantern/files/14134985/Lantern_dev_v1.5.zip)
> 
> Please note that this is an in-dev build so there may be other issues. I'm currently working on other features.

Works well with ExportPal function. Because I only use this function, I am not sure how other functions work. I am very sorry for this.

**Comment by CerisWhite** [comment]
That's fine. If it works for that one, that's a good sign it'll work with all of them. The reason the error came up would have to be because I was using 32bit builds, so I guess I'll have to start using 64bit instead going forward.
